### ISSUE TITLE
여러 장치 접속 문제

### ISSUE THREAD

**Issue by dalek7** [Hyeonzoo/AppInventor_ArduinoBLE#1]
디바이스 접속 목록 관리가 안되는 느낌입니다. 일단 되면 동작은 잘 되는데, 한번 살펴봐주세요.

**Comment by Hyeonzoo** [comment]
연결된 디바이스 목록 기능 추가하였습니다!

[https://github.com/Hyeonzoo/AppInventor_ArduinoBLE/blob/main/05_Two_Board_Serial_Monitor/App_BLE_two_board_Serial_Monitor_v3.aia](url)
